name: Deploy to Amazon ECR

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

env:
  AWS_REGION: ap-northeast-2
  ECR_REGISTRY: 442426889907.dkr.ecr.ap-northeast-2.amazonaws.com
  ECR_REPOSITORY: web-site

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build, tag, and push image to Amazon ECR
      id: build-image
      run: |
        GIT_HASH=$(git rev-parse --short "$GITHUB_SHA")
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$GIT_HASH .
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$GIT_HASH
        echo "::set-output name=image::$ECR_REGISTRY/$ECR_REPOSITORY:$GIT_HASH"

    - name: repository checkout
      uses: actions/checkout@v2
      with:
        repository: ${{ github.repository_owner }}/argocd-kube
        token: ${{ github.token }}
        path: gitops-argocd
        fetch-depth: 0

    - name: Fix image tag
      working-directory: gitops-argocd
      run: |
        GIT_HASH=$(git rev-parse --short "$GITHUB_SHA")
        sed -i "16s/.*/        - image: $ECR_REGISTRY\/$ECR_REPOSITORY:$GIT_HASH/g" deployment.yaml
        cat deployment.yaml

    - name: Commit and push
      uses: actions-js/push@v1.5
      with:
        github_token: ${{ secrets.MY_GITHUB_TOKEN }}
        message: Inject Tag
        directory: gitops-argocd
        repository: ${{ github.repository_owner }}/argocd-kube
